### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by GAIYA2050** [2010511951/Occlusion_test#1]
Can I get the dataset
image_pair = ["Occlusion_test/dataset/sob_lateral.bmp","Occlusion_test/dataset/Doc3_lateral.bmp"]

**Comment by 2010511951** [comment]
Sure

**Comment by GAIYA2050** [comment]
请问这两张图片之间试啥关系呢
生成哪个的遮挡图啊

**Comment by GAIYA2050** [comment]
如果方便的话能否请您联系下QQ:109742623 或者我联系您,报酬好商量

**Comment by GAIYA2050** [comment]
qq错了:1097425623
